config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  validates :user, :text, presence: true
  validates :user, :text, length: {maximum: 255}

end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new
  USERNAME_FORMAT = /\A\w+\z/

  attr_accessor :password

  has_many :questions, dependent: :destroy
  has_many :asked_questions, class_name: 'Question', foreign_key: :author_id, dependent: :nullify

  before_save :encrypt_password
  before_validation :downcase_username, :downcase_email

  validates :email, :username, presence: true
  validates :email, :username, uniqueness: true
  validates :password, presence: true, on: :create
  validates :password, confirmation: true
  validates :username, length: { maximum: 40 }, format: { with: USERNAME_FORMAT}
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  validates :avatar_url, format: { with: URI::DEFAULT_PARSER.make_regexp, allow_blank: true }
  validates :profile_color, format: { with: /\A#\h{6}\z/ }

  def self.hash_to_string(password_hash)
    password_hash.unpack("H*")[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email&.downcase)

    return unless user.present?    

    hashed_password = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST
      )
    )
    user if user.password_hash == hashed_password

  end

  private

  def downcase_username
    username&.downcase!
  end

  def downcase_email
    email&.downcase!
  end

  def encrypt_password
    return if password.blank?

    self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

    self.password_hash = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, password_salt, ITERATIONS, DIGEST.length, DIGEST
      )
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Чтобы метод current_user был доступен в шаблона, нам необходимо объявить
  # его с помощью метода helper_method. Эта строка как бы говорит рельсам:
  # если в шаблоне встретишь current_user — не пугайся, что такого метода нет,
  # дерни этот метод у контроллера.
  helper_method :current_user

  private

  # Метод контроллера, достающий текущего юзера из базы по данным аутентификации
  # в сессии.
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # Метод, который редиректит посетителя на главную с предупреждением о
  # нарушении доступа. Мы будем использовать этот метод, когда надо запретить
  # пользователю что-то.
  def reject_user
    redirect_to root_path, alert: 'Вам сюда низя!'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :load_question, only: %i[ show edit update destroy ]
  before_action :authorize_user, except: [:create]

  def edit
  end

  def create
    @question = Question.new(question_params)

    @question.author = current_user

    if @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан'
    else        
      render :edit
    end
  end

  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен'
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy

    redirect_to user_path(user), notice: 'Вопрос удален'
  end

  private
    def load_question
      @question = Question.find(params[:id])
    end

    def authorize_user
      reject_user unless @question.user == current_user
    end

    def question_params
      if current_user.present? && params[:question][:user_id].to_i == current_user.id
        params.require(:question).permit(:user_id, :text, :answer)
      else
        params.require(:question).permit(:user_id, :text)
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: 'вы успешно залогинились'
    else
      flash.now.alert = 'Неправильный мэйл или пароль'
      render :new   
    end   
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Вы разлогинились! приходи еще!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :create, :new]

  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
  end

  def new
    redirect_to root_path, alert: 'Вы уже залогинены' if current_user.present?

    @user = User.new
  end

  def create
    redirect_to root_path, alert: 'Вы уже залогинены' if current_user.present?

    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Вы успешно зарегистрировались"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены'
    else
      render 'edit'
    end
  end

  def show
    @questions = @user.questions.order(created_at: :desc)

    @new_question = @user.questions.build

    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: "Вы успешно удалили свой аккаунт"
  end
  
  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :avatar_url, :profile_color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
  	if user.avatar_url.present?
  	  user.avatar_url
  	else
      asset_path 'avatar.png'
    end
  end
  
  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end

  def inclination(number, one, few, many)
    return many if (number % 100).between?(11, 14)

    case number % 10
    when 1 then one
    when 2..4 then few
    else many
    end
  end
  
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>Вопросы кучки друзей</title>
  <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
</head>
<body>
<div class="header">
  <div class="container">
    <div class="header-logo">
      <h1 class="header-title"><%= link_to "Вопросы кучки друзей", root_path %></h1>
    </div>

    <%# Выводим в хэдере информацию для логина/авторизации/регистрации %>
    <div class="header-nav">
      <%# Если есть текущий юзер (значит он залогинен) %>
      <% if current_user %>
        <%# Даем ссылки на его профиль и на логаут %>
        <%= link_to "@#{current_user.username}", user_path(current_user) %> |
        <%= link_to 'Выйти', session_path, data: {method: :delete} %>
      <% else %>
        <%# Если нету — ссылки на регистрацию и логин %>
        <%= link_to 'Зарегистрироваться', new_user_path,
          class: 'button button-light button-small' %>
        <%= link_to 'Войти', new_session_path,
          class: 'button button-light button-small' %>
      <% end %>
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    <%# Выводим сообщение об ошибке или уведомление для пользователя. %>
    <%# Если в объеккте flash есть что-то, выводим содержимое на страницу, %>
    <%# если нет, игнорируем этот блок. %>
    <% if flash.any? %>
      <div class="content-wrapper buffer-both">
        <% flash.each do |name, message| %>
          <%= content_tag :div, message, class: "flash-#{name}" %>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%# Скрытое поле — айдишник юзера, кому задается вопрос %>
    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, 'Вопрос', class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <%# Простая авторизация - может ли текущий юзер править вопрос? %>
    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>
    
    <%# Хелпер капчи %>
    <%#= recaptcha_tags unless current_user.present? %>

    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer %>
      </div>
    <% end %>

    <div class="question-author">
      <% questioner = question.author %>
      
      <% if questioner %>
        <%= link_to questioner.username, user_path(questioner) %>
      <%else%>
        <span>Анонимус</span>
      <% end %>
    </div>

    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>
  </div>

  <% if question.user == current_user %>
    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

    <div class="question-actions">
      <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<%# Страница редактирования вопроса %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%# Подключаем паршиал app/views/questions/_form.html.erb %>
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<%# Страница редактирования пользователя %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for(@user) do |f| %>
      <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
      <%# в поле errors модели (в нашем случае @users). %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%# С помощью методов label и text_field у объекта f мы создаем теги %>
      <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <%# Поступаем аналогично для других полей %>
      <div class="form-field">
        <%= f.label :name, class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :avatar_url, class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :profile_color, class: 'form-label' %>
        <%= f.color_field :profile_color %>
      </div>

      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, value: nil, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>
      
      <div class="form-action buffer-top space-between">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
        <%= link_to 'Удалить аккаунт', user_path(@user), 
        method: :delete, data: { confirm: 'Вы уверены?' }, 
        class: 'button button-small button-danger' %>
        
      </div>
    <% end %>

    <%# Подробнее про помощники для создания форм: %>
    <%# http://guides.rubyonrails.org/form_helpers.html %>
  </div>
</div>

app/views/users/index.html.erb
<%# Этот шаблон отрисуется, когда посетитель захочет посмотреть список %>
<%# пользователей на странице /users (users#index) %>
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <%# Этот код выводит каждого пользователя в цикле %>
  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%# Пользуемся аж четырьмя хелперами: %>
        <%# * link_to — генерирует ссылку %>
        <%# * image_tag — генерирует картинку %>
        <%# * user_avatar — достает из пользователя ссылку на картинку %>
        <%#   или подставляет дефолтную %>
        <%# * user_path(user) возвращает относительный путь страницы %>
        <%#   пользователя, например /users/1 %>
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%# Страница для регистрации нового пользователя. %>

<%# Обратите внимание, что она очень похожа на страницу редактирования юзера, %>
<%# что позволяет в подобных случаях использовать один и тот же паршиал form %>
<%# в обоих страницах. %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for @user do |f| %>
      <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
      <%# в поле errors модели (в нашем случае @users). %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%# С помощью методов label и text_field у объекта f мы создаем теги %>
      <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <%# Поступаем аналогично для других полей %>
      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>

    <%# Подробнее про помощники для создания форм: %>
    <%# http://guides.rubyonrails.org/form_helpers.html %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background: <%= @user.profile_color %>">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>
</div>

<div class="user-details">
  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>

  <%# Выводим счетчики вопросов в три колонки. Обратите внимание, что тут %>
  <%# в пору использовать наш любимый склонятор. На эту тему смотрите ДЗ. %>
  <div class="user-statistics container text-center">
    <div class="column-1-3">
      <h1 class="title-small"><%= @questions_count %></h1>
      <p><%= inclination(@questions.size, 'вопрос', 'вопроса', 'вопросов') %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @answers_count %></h1>
      <p><%= inclination(@answers_count, 'ответ', 'ответа', 'ответов') %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @unanswered_count %></h1>
      <p><%= inclination(@unanswered_count, 'безответный вопрос', 'безответных вопроса', 'безответных вопросов') %></p>
    </div>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <%= form_for @new_question do |f| %>
      <%= f.hidden_field :user_id %>

      <div class="form-field">
        <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea' %>
      </div>

      <%# Хелпер капчи %>
      <%#= recaptcha_tags size: 'compact' unless current_user.present? %>
      
      <div class="form-action">
        <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>